// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_tPJWryz6s2W51SOigS03RdEH9N5lH24',
    appId: '1:999680168118:web:a662a927f931dfb6641617',
    messagingSenderId: '999680168118',
    projectId: 'trackit-db05a',
    authDomain: 'trackit-db05a.firebaseapp.com',
    storageBucket: 'trackit-db05a.firebasestorage.app',
    databaseURL: 'https://trackit-db05a-default-rtdb.firebaseio.com',
  );

  // ✅ ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_DFerZxJkVMSS-mq36Ri0bikSf6c26js',
    appId: '1:999680168118:android:fc69f2bd2aef8c4e641617',
    messagingSenderId: '999680168118',
    projectId: 'trackit-db05a',
    storageBucket: 'trackit-db05a.firebasestorage.app',
    databaseURL: 'https://trackit-db05a-default-rtdb.firebaseio.com',
  );

  // ✅ IOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZQzdTnBi5vM5nT57o-w0LBdboskdIBU',
    appId: '1:999680168118:ios:cca4a963fb956337641617',
    messagingSenderId: '999680168118',
    projectId: 'trackit-db05a',
    storageBucket: 'trackit-db05a.firebasestorage.app',
    databaseURL: 'https://trackit-db05a-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.trackit',
  );

  // ✅ MACOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZQzdTnBi5vM5nT57o-w0LBdboskdIBU',
    appId: '1:999680168118:ios:cca4a963fb956337641617',
    messagingSenderId: '999680168118',
    projectId: 'trackit-db05a',
    storageBucket: 'trackit-db05a.firebasestorage.app',
    databaseURL: 'https://trackit-db05a-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.trackit',
  );

  // ✅ WINDOWS
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_tPJWryz6s2W51SOigS03RdEH9N5lH24',
    appId: '1:999680168118:web:bdcf0569a0af8a46641617',
    messagingSenderId: '999680168118',
    projectId: 'trackit-db05a',
    authDomain: 'trackit-db05a.firebaseapp.com',
    storageBucket: 'trackit-db05a.firebasestorage.app',
    databaseURL: 'https://trackit-db05a-default-rtdb.firebaseio.com',
  );
}